import { Injectable } from '@angular/core';

import type { RuntimeConfig } from '../../domain/models/runtime-config.model';
import { environment } from '../../../environments/environment';

/**
 * Loads runtime configuration from /assets/config.json at app startup.
 *
 * In Docker deployments, config.json is generated by the entrypoint script
 * from environment variables (e.g. API_URL), allowing runtime configuration
 * without rebuilding the Angular app.
 *
 * Falls back to environment.ts values if config.json is not available.
 */
@Injectable({ providedIn: 'root' })
export class RuntimeConfigService {
  private config: RuntimeConfig = {
    apiBaseUrl: environment.apiBaseUrl,
  };

  get apiBaseUrl(): string {
    return this.config.apiBaseUrl;
  }

  async load(): Promise<void> {
    try {
      const response = await fetch('/assets/config.json');
      if (response.ok) {
        const json = (await response.json()) as Partial<RuntimeConfig>;
        if (json.apiBaseUrl) {
          this.config = { ...this.config, ...json };
        }
      }
    } catch {
      // config.json not available — use environment.ts defaults
    }
  }
}
